### ISSUE TITLE
Can you make this to web generate online?

### ISSUE THREAD

**Issue by ghost** [bbredesen/mjson2go#1]
Something like this https://mholt.github.io/json-to-go/ 

Thank you

**Comment by bbredesen** [comment]
I don't know if the use case makes sense...I imagined this being used in a build process via "go generate", so you could debug/modify the pipeline alongside your Go source.

Having said that, I'll play around with Go/WASM and see what it would take to refactor/host it as a github page.

**Comment by bbredesen** [comment]
Online version is now live at https://bbredesen.github.io/mjson2go/
