### ISSUE TITLE
Can you make the go output support Key/Value in bson.D

### ISSUE THREAD

**Issue by shanehughes1990** [bbredesen/mjson2go#2]
First of all I want to say thank you... lol I was about to go down this road myself and create one, I have a request I can't off the top my head remember which go tool is causing the errors but when you use bson.D although yours works, and I used it to generate a 2500 line aggregate so thank you for that lol.

but this is an example of the output it generated.

```
bson.A{
	bson.D{
		{"$match", bson.D{
			{"companyId", companyId},
			{"_id", id},
		}},
	},
}
```
I think it's the go linter in vscode that complains but to get it go stop I have to change from that example to this
```
bson.A{
	bson.D{
		{Key: "$match", Value: bson.D{
			{Key: "companyId", Value: companyId},
			{Key: "_id", Value: payrollId},
		}},
	},
}
```
Where ever bson.D is used you literally put `Key: "whatever", Value: "whatever"` the value can be anything, another bson.D, bson.A string etc etc...
But this stops the linter from complaining and works the same.

Also side note I know technically it's the same thing, but mongo go driver has a mongo.Pipeline type which = []bson.D which is what I think for clarity should be used in the aggregate cursor (although that may just be personal preference)
for example
```
db.Collection("test").Aggregate(
	ctx, 
	mongo.Pipeline{
		bson.D{
			{Key: "$match", Value: bson.D{
				{Key: "companyId", Value: companyId},
				{Key: "_id", Value: payrollId},
			}},
		},
	},
)
```
![image](https://user-images.githubusercontent.com/31993465/180038759-f307dbaf-2adb-4051-8f4f-2d4df56432ce.png)

**Comment by bbredesen** [comment]
Took 9 months to get around to this, but thank you for the suggestions and the changes have been made. New version v0.3.0 with the updates has been tagged and released.

**Comment by shanehughes1990** [comment]
That's exciting I was starting to wonder if this was a dead ticket. Thanks for the update I use your tool daily!
